USE ecommerce_db;

SELECT * FROM products;
SELECT product_name, price FROM products WHERE price > 1000;
SELECT product_name, price FROM products ORDER BY price DESC;
SELECT COUNT(*) AS total_customers FROM customers;
SELECT COUNT(*) AS total_products FROM products;
SELECT SUM(stock) AS total_stock FROM products;
SELECT AVG(price) AS average_price FROM products;
SELECT category, COUNT(*) AS product_count FROM products GROUP BY category;
SELECT category, AVG(price) AS average_price FROM products GROUP BY category HAVING AVG(price) > 3000;
SELECT c.first_name, c.last_name, o.order_id, o.order_date FROM customers c INNER JOIN orders o ON c.customer_id=o.customer_id;
SELECT c.first_name, c.last_name, o.order_id FROM customers c LEFT JOIN orders o ON c.customer_id=o.customer_id;
SELECT c.first_name, c.last_name, o.order_id FROM customers c RIGHT JOIN orders o ON c.customer_id=o.customer_id;
SELECT first_name, last_name FROM customers WHERE phone IS NULL;
SELECT first_name, COALESCE(phone,'Not Available') AS phone FROM customers;
SELECT first_name, NULLIF(city,'') AS city FROM customers;
SELECT CONCAT(first_name,' ',last_name) AS full_name FROM customers;
SELECT UPPER(first_name) AS first_name_upper, LOWER(email) AS email_lower FROM customers;
SELECT product_name, LENGTH(product_name) AS name_length FROM products;
SELECT order_id, YEAR(order_date) AS order_year, MONTH(order_date) AS order_month FROM orders;
SELECT c.customer_id, CONCAT(c.first_name,' ',c.last_name) AS customer_name, COALESCE(SUM(oi.quantity*oi.unit_price),0) AS total_spend FROM customers c LEFT JOIN orders o ON c.customer_id=o.customer_id LEFT JOIN order_items oi ON o.order_id=oi.order_id GROUP BY c.customer_id,c.first_name,c.last_name;
SELECT p.product_name, SUM(oi.quantity) AS units_sold FROM products p JOIN order_items oi ON p.product_id=oi.product_id GROUP BY p.product_id,p.product_name ORDER BY units_sold DESC;
SELECT p.product_name, SUM(oi.quantity*oi.unit_price) AS revenue FROM products p JOIN order_items oi ON p.product_id=oi.product_id GROUP BY p.product_id,p.product_name ORDER BY revenue DESC LIMIT 5;
SELECT c.customer_id, CONCAT(c.first_name,' ',c.last_name) AS customer_name, COUNT(o.order_id) AS order_count FROM customers c LEFT JOIN orders o ON c.customer_id=o.customer_id GROUP BY c.customer_id,c.first_name,c.last_name;
SELECT c.customer_id, CONCAT(c.first_name,' ',c.last_name) AS customer_name, SUM(oi.quantity*oi.unit_price) AS total_spend FROM customers c JOIN orders o ON c.customer_id=o.customer_id JOIN order_items oi ON o.order_id=oi.order_id GROUP BY c.customer_id,c.first_name,c.last_name HAVING SUM(oi.quantity*oi.unit_price)>10000;
SELECT product_name, price FROM products WHERE price>(SELECT AVG(price) FROM products);
SELECT p.product_name,p.price,p.category FROM products p WHERE p.price>(SELECT AVG(p2.price) FROM products p2 WHERE p2.category=p.category);
SELECT c.first_name,c.last_name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id);
SELECT c.first_name,c.last_name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id);
SELECT product_name,price,CASE WHEN price>=50000 THEN 'Premium' WHEN price>=10000 THEN 'Mid Range' ELSE 'Budget' END AS price_category FROM products;
SELECT p.product_name,RANK() OVER (ORDER BY SUM(oi.quantity) DESC) AS sales_rank FROM products p JOIN order_items oi ON p.product_id=oi.product_id GROUP BY p.product_id,p.product_name;
SELECT c.first_name,c.last_name,DENSE_RANK() OVER (ORDER BY SUM(oi.quantity*oi.unit_price) DESC) AS spending_rank FROM customers c JOIN orders o ON c.customer_id=o.customer_id JOIN order_items oi ON o.order_id=oi.order_id GROUP BY c.customer_id,c.first_name,c.last_name;
SELECT o.order_id,o.order_date,SUM(oi.quantity*oi.unit_price) AS order_total,LAG(SUM(oi.quantity*oi.unit_price)) OVER (ORDER BY o.order_date) AS previous_order_total FROM orders o JOIN order_items oi ON o.order_id=oi.order_id GROUP BY o.order_id,o.order_date;
SELECT o.order_id,o.order_date,SUM(oi.quantity*oi.unit_price) AS order_total,LEAD(SUM(oi.quantity*oi.unit_price)) OVER (ORDER BY o.order_date) AS next_order_total FROM orders o JOIN order_items oi ON o.order_id=oi.order_id GROUP BY o.order_id,o.order_date;
SELECT customer_id,SUM(total_spend) AS total_spend,NTILE(4) OVER (ORDER BY SUM(total_spend) DESC) AS customer_quartile FROM (SELECT c.customer_id,SUM(oi.quantity*oi.unit_price) AS total_spend FROM customers c JOIN orders o ON c.customer_id=o.customer_id JOIN order_items oi ON o.order_id=oi.order_id GROUP BY c.customer_id) x GROUP BY customer_id;
SELECT city FROM customers WHERE city IS NOT NULL UNION SELECT shipping_city FROM orders WHERE shipping_city IS NOT NULL;
SELECT category,SUM(quantity*unit_price) AS revenue FROM products p JOIN order_items oi ON p.product_id=oi.product_id GROUP BY ROLLUP(category);
SELECT category,supplier,SUM(stock) AS total_stock FROM products GROUP BY GROUPING SETS ((category),(supplier),());
CREATE OR REPLACE VIEW customer_spending_report AS SELECT c.customer_id,CONCAT(c.first_name,' ',c.last_name) AS customer_name,COALESCE(SUM(oi.quantity*oi.unit_price),0) AS total_spend FROM customers c LEFT JOIN orders o ON c.customer_id=o.customer_id LEFT JOIN order_items oi ON o.order_id=oi.order_id GROUP BY c.customer_id,c.first_name,c.last_name;
SELECT * FROM customer_spending_report;
ALTER TABLE products ADD COLUMN discount_percent DECIMAL(5,2) DEFAULT 0;
ALTER TABLE products ADD CONSTRAINT chk_discount CHECK (discount_percent BETWEEN 0 AND 100);
SELECT product_name,price,price*(1-discount_percent/100) AS discounted_price FROM products;
SELECT status,COUNT(*) AS order_count FROM orders GROUP BY status HAVING COUNT(*)>=2;
SELECT p.category,COUNT(DISTINCT o.order_id) AS orders_count FROM products p JOIN order_items oi ON p.product_id=oi.product_id JOIN orders o ON oi.order_id=o.order_id GROUP BY p.category;
SELECT p.product_name,AVG(r.rating) AS average_rating FROM products p LEFT JOIN reviews r ON p.product_id=r.product_id GROUP BY p.product_id,p.product_name ORDER BY average_rating DESC;
